overwrite: true

projects:
  example:
    schema:
      - https://graphql.api.apollographql.com/api/graphql
    documents: src/graphql/example/**/*.gql
    extensions:
      codegen:
        generates:
          src/generated/graphql-example/generated.ts:
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node
